apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: github-actions-for-ci
  annotations:
    github.com/project-slug: TomerAdmon/github-actions-for-ci
spec:
  type: other
  lifecycle: unknown
  owner: guests
